### ISSUE TITLE
Bus Stop Details

### ISSUE THREAD

**Issue by pushpakrajgautam** [tachyons/bmtc_api#9]
Hey!

I tried making a post request to get stop details using the stopid data param, but it gave me a 404 error. Is this still functioning or has it been deprecated?

Thanks!

**Comment by tachyons** [comment]
This API is extracted from BMTC mobile app, and can change any time. Can you please share exact parameters you used for testing?

**Comment by pushpakrajgautam** [comment]
Hey!

No worries, I figured this out. I wasn't sending the right request body.

Thanks!

**Comment by tachyons** [comment]
Welcome
